### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by kwoot** [k0lter/autopostgresqlbackup#1]
Hi,

I have a few feature requests for this script that I sort of install on every server I setup:

- Compress dump file during creation of dump. Due to large dumps really dipping filespace before zipping.
- Option to disable weekly, montly backups. Due to sometimes going back more than a week is just not an option but daily backups are very much needed.

Kind regards,
Jeroen Baten

**Comment by PurplePingu** [comment]
It would also be great to capture the database permissions as well.
This might require use of pg_dump --schema-only to a seperate file from what I saw at https://dba.stackexchange.com/questions/132610/export-roles-with-privileges-under-postgresql-9-3

**Comment by k0lter** [comment]
@kwoot I've just pushed some changes (they will be part of version 2.0) which addressed your feature requests. See [Changelog.md](https://github.com/k0lter/autopostgresqlbackup/blob/master/Changelog.md) for details.

**Comment by k0lter** [comment]
@PurplePingu This is already supported, PostgreSQL globals are dumped into a "virtual database" named postgres-gloabals.

**Comment by k0lter** [comment]
I'm closing this bug as it is already solved.
