### ISSUE TITLE
Problem decrypting large databases

### ISSUE THREAD

**Issue by foarsitter** [k0lter/autopostgresqlbackup#10]
When trying to decrypt a large file (1.9GB )with `openssl smime` an error occurs: https://github.com/openssl/openssl/issues/2515

It seems that files larger than 1.5GB cannot be decrypted.

**Comment by k0lter** [comment]
It's not directly an autopostgresqlbackup bug but I could add some help/doc/link to point https://github.com/imreFitos/large_smime_decrypt (a tool able to decrypt files larger than 1.5 GB) in such case.

**Comment by foarsitter** [comment]
Tried that one but without of luck: 
```
40778C6D837F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:../providers/implementations/ciphers/ciphercommon_block.c:124:

```

**Comment by k0lter** [comment]
What is the size of your file? (Maybe taking a look at https://kasunc.medium.com/fantastic-openssl-and-taming-hidden-beasts-inside-smime-bbeef14d02ea, there is a openssl static binary to decrypt files under 3GB).

**Comment by foarsitter** [comment]
The file is 1.9GB, the static binary seems a good solution. Lucky we are not in recovery :)

**Comment by k0lter** [comment]
Use OpenSSL to encrypt databases dumps is no longer safe so I will probably switch to gpg.

I was able to encrypt/decrypt (`--symmetric --cipher-algo aes256`) a 4GB file without any issue.

**Comment by k0lter** [comment]
I'm closing this bug as it is already solved.
