### ISSUE TITLE
Problem in v2: $OPTS also passed to pgdumpall, so -Fc fails

### ISSUE THREAD

**Issue by hyperman2** [k0lter/autopostgresqlbackup#12]
We run the debian/ubuntu version of this script with option -Fc to create .pgdump files instead of .sql files.  In the v2 version, this fails:  $OPTS is not only passed to pg_dump, but also to pg_dumpall.  And theoptions for these 2 programs are not the same.

I'd suggest passing OPTS to only pg_dump, and add a new config variable OPS_PGDUMPALL or something.

Related bonus issue: the v1.1 version does not support pg_dump -Fd (which would allow parallel backups): changing rights on a directory failed.

**Comment by k0lter** [comment]
You're right, I will separate OPTS for pg_dump and pg_dumpall

I will also take a look for `-Fd` option

**Comment by k0lter** [comment]
I've pushed a fixed.

See [Changelog](https://github.com/k0lter/autopostgresqlbackup/blob/master/Changelog.md) for the new options.

**Comment by hyperman2** [comment]
This works perfectly.  Thanks.
