### ISSUE TITLE
Feature request in v2:  Enable troubleshooting flags in config files

### ISSUE THREAD

**Issue by hyperman2** [k0lter/autopostgresqlbackup#16]
I can set DEBUG="yes" only by modifying the script.  I'd like to be able to set it from  /etc/default/autopostgresqlbackup.  Additionaly, a flag to disable the rm -f "${LOG_FILE}" would be much appreciated while troubleshooting

**Comment by k0lter** [comment]
I have to take a look on how use this flag with the `-d` command line argument.

**Comment by hyperman2** [comment]
OK, didn't know there was a flag.  BTW, the link on the main page to the documentation is broken:

https://github.com/k0lter/autopostgresqlbackup/blob/master/Documenation.md

is missing a t

**Comment by k0lter** [comment]
I've fixed the link. Thanks.
