### ISSUE TITLE
Feature request in v2: Make the path to the config file configurable

### ISSUE THREAD

**Issue by hyperman2** [k0lter/autopostgresqlbackup#17]
The config file is today hardcoded to /etc/default/autopostgresqlbackup 

If I could provide a config file on the command file, I could schedule multiple instances of autopostgresqlbackup in cron, backing up different postgres clusters from the same machine.  

Workaround:  The config file is a script file, so it can switch between configs based on an environment variable.

**Comment by hyperman2** [comment]
I just logged 6 bugs/feature requests.  If I ever meet @k0lter  in real life, I should buy you  cookies.  Thanks for this script!

**Comment by k0lter** [comment]
That's planned. The middle term plan is to rename this tool autodbbackup and the v2 rewrite will permit to easily backup others databases engines like MySQL, Mongo, Influx, etc.

There  will probably be a `/etc/autobackup.d/` directory with config files like `/etc/default/autopostgresqlbackup`  with default configuration for supported databases engines but also to add your own.

As an example:
- `/etc/default/autopostgresqlbackup` could become `/etc/autobackup.d/postgresql.conf`
- I could add  `/etc/autobackup.d/{mysql,mongdb}.conf` the same way
- It could be possible if you have a Pg Cluster to duplicate  (multiple times if needed) `/etc/autobackup.d/postgresql.conf` and ajust settings

**Comment by ieugen** [comment]
I like the plan, but are you sure you want to build a generic db backup tool in bash? 

IMO it's not the best language to write complex software in. 
Maintenance is quite hard IMO.

**Comment by k0lter** [comment]
@hyperman2 @ieugen I'm closing this issue as it was fixed a few weeks ago (see 81614646bc654c508770f3108891d1e348ac9b59).

**Comment by Hansyperman** [comment]
Thanks
