### ISSUE TITLE
Correct cleanup() tail filter

### ISSUE THREAD

**Issue by jhowe-uw** [k0lter/autopostgresqlbackup#19]
tail +${count} generates an error on RHEL 6-8 systems. Make intent explicit with "-n +${count}"

```
+++ b/files/usr/local/sbin/autopostgresqlbackup
@@ -475,7 +475,7 @@ cleanup() {
         sed -r 's/^.+([0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}h[0-9]{2}m).*$/\1 \0/'
         sort -r | \
         sed -r -n 's/\S+ //p' | \
-        tail "+${count}" | \
+        tail "-n +${count}" | \
         xargs -L1 rm -fv | \
         while IFS= read -r line ; do
             log_info "${line}"
```

**Comment by TheFlipside** [comment]
@jhowe-uw thanks so much for this fix, it was bugging me for the longest time in my report emails.

@k0lter fyi, with the current default the report contains multiple instances of "tail: cannot open '+14' for reading: No such file or directory".
It would be nice if this change could be applied to main

**Comment by k0lter** [comment]
@jhowe-uw This is fixed with my last commit. Thanks for your feedback.

**Comment by k0lter** [comment]
I'm closing this bug as it is already solved.
