### ISSUE TITLE
Support multiple hosts

### ISSUE THREAD

**Issue by naoliv** [k0lter/autopostgresqlbackup#21]
Would it be possible to add support for multiple hosts, please?

For example, we could have the hosts separated by commas (or another separator) and, for each host, run the same backup process.

```
# Host names (or IP addresses) of PostgreSQL servers e.g localhost
DBHOST=server1, server2, server3
```

**Comment by ieugen** [comment]
Looking forward to having this feature. 
I think I can have a workaround for this IMO. 
I'm planning to run the script from docker and would be able to provide configuration as a volume mount.

**Comment by k0lter** [comment]
@naoliv @ieugen It's been implemented in the last commits, see ([documentation](https://github.com/k0lter/autopostgresqlbackup/blob/master/Documentation.md), the `-c` argument and the ([examples](https://github.com/k0lter/autopostgresqlbackup/blob/master/examples/) directory.

**Comment by k0lter** [comment]
@naoliv @ieugen I'm closing this issue as I think that it's now fixed. Don't hesitate to reopen it if you think it deserves it.
