### ISSUE TITLE
add support for pigz as compression type

### ISSUE THREAD

**Issue by DanScharon** [k0lter/autopostgresqlbackup#3]
Adding support for pigz as compression type would immensely speed up  the compression on systems with multiple cores.

**Comment by k0lter** [comment]
I've just pushed some changes (they will be part of version 2.0) which addressed your feature request: Any compression tool that supports to read data to be compressed from stdin and outputs it to stdout is now supported.

**Comment by k0lter** [comment]
I'm closing this bug as it is already solved.
