### ISSUE TITLE
Not available in debian 11 (bullseye)

### ISSUE THREAD

**Issue by VeselaHouba** [k0lter/autopostgresqlbackup#7]
I have no idea what's the process of adding packages to repos. If someone can point me where to start, I'll be glad to do the work.

**Comment by claudep** [comment]
It will be available again in debian 12, but yes, a backport for debian 11 would be nice!

**Comment by k0lter** [comment]
@VeselaHouba @claudep It should be available in a few days in bullseye-backports (waiting for approval by the Debian Backports team).

**Comment by k0lter** [comment]
I'm closing this bug as it is already solved.
