### ISSUE TITLE
Add optional rotation for monthly backups

### ISSUE THREAD

**Issue by claudep** [k0lter/autopostgresqlbackup#8]

**Comment by craigconstantine** [comment]
this would be nice! I'd love to be able to entirely disable monthly backups too…

we're covering the daily backups with our larger system backups, so I don't need weekly nor monthly dumps...

**Comment by k0lter** [comment]
@claudep @craigconstantine I've just pushed some changes (they will be part of version 2.0) which addressed your feature requests. See [Changelog.md](https://github.com/k0lter/autopostgresqlbackup/blob/master/Changelog.md) for details.

**Comment by claudep** [comment]
Fixed by ff233cabef69 with `BRMONTHLY` new config variable. @k0lter, thanks so much for developing and maintaining the package. Tu es notre héros :-)

**Comment by craigconstantine** [comment]
Awesome. Thanks so much!! :D
